### ISSUE TITLE
[Custom Agent Deployer] When docker-compose file has build instruction, Dockerfile is expected in the elastic-package path 

### ISSUE THREAD

**Issue by agithomas** [elastic/elastic-package#1007]
When docker-compose file has build instruction, Dockerfile is expected in the elastic-package path 

~/.elastic-package/deployer/docker_custom_agent

```
version: '2.3'
services:
docker-custom-agent:
build:
      context: .
      dockerfile: Dockerfile.oracle
user: root
oracle:
image: docker.elastic.co/observability-ci/database-enterprise:12.2.0.1
ports:
- 1521:1521
- 5500:5500
```

elastic-package lint will create an error as below

`unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/agikthomas/.elastic-package/deployer/docker_custom_agent/Dockerfile: no such file or directory
ERROR: Service 'docker-custom-agent' failed to build : Build failed
`
