### ISSUE TITLE
[Custom Agent Deployer] Custom agent deployer needs ES version set statically

### ISSUE THREAD

**Issue by agithomas** [elastic/elastic-package#1027]
Custom agent deployer needs ES version set statically. If the custom-agent is value is not compatible with to establish the communication with ES, it will lead to enrolment failure. 

Need enhancement to support service deployer configuration as below

```
version: '2.3'
services:
  docker-custom-agent:
    build:
      context: .
      args:
        VERSION: ${ES_AGENT_VERSION:-8.3.0}
      dockerfile: Dockerfile
    image: elastic-agent-oracle-client-1
    depends_on:
      oracle:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'select sysdate from dual;' | ORACLE_HOME=/opt/oracle/instantclient_21_4 /opt/oracle/instantclient_21_4/sqlplus -s sys/Oradoc_db1@oracle:1521/ORCLCDB.localdomain as sysdba"]
      interval: 120s
      timeout: 300s
      retries: 300
```
