### ISSUE TITLE
Add CA fingerprint to agents configuration in 8.x versions

### ISSUE THREAD

**Issue by agithomas** [elastic/elastic-package#1083]
The request is to support stand along agents connect with elastic stack created using `elastic-package stack up` over https.

These setting is needed in the default profile . This comes to use only when` --certificate-authorities=$ELASTIC_PACKAGE_CA_CERT`   flag is present when adding the agent. 

The configuration goes as below

```
xpack.fleet.outputs:
  - id: fleet-default-output
    name: default
    type: elasticsearch
    hosts: [ https://elasticsearch:9200/ ]
    # openssl x509 -fingerprint -sha256 -noout -in tls/kibana/elasticsearch-ca.pem (colons removed)
    ca_trusted_fingerprint: <fingerprint generated using $ELASTIC_PACKAGE_CA_CERT>
    is_default: true
    is_default_monitoring: true
```
