### ISSUE TITLE
[TSDB] Dimension limit override settings blocking the build

### ISSUE THREAD

**Issue by agithomas** [elastic/elastic-package#1174]
Refer : https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-5312/12/pipeline

The configuration to override the default limit is provided as 

```
elasticsearch:
  index_template:
    settings:
      index.mapping.dimension_fields.limit: 32
```

Inspite this is a valid configuration, the integration test error appears. This may have an impact on more than one packages , not just limited to the influxdb.
