### ISSUE TITLE
Support for external dependencies in input packages

### ISSUE THREAD

**Issue by jsoriano** [elastic/elastic-package#1224]
Input packages can define fields. If they are external, they are not resolved and it is silently ignored.
We should have the same behaviour as with integration packages, if an external field cannot be resolved for any reason, build should fail.

**Comment by mrodm** [comment]
This issue also affects integration packages.

If `_dev/build/build.yml` file does not exist, or the ECS reference is not defined, packages are built without any error, but the field definitions are not resolved, for instance:

```yaml
 $ cat ../../build/packages/elastic_package_registry/0.0.11/data_stream/metrics/fields/ecs.yml 
- name: ecs.version
  external: ecs
- name: error.message
  external: ecs
- name: event.duration
  external: ecs
- name: event.ingested
  external: ecs
- name: event.kind
  external: ecs
- name: service.address
  external: ecs
- name: service.type
  external: ecs
- name: tags
  external: ecs
```

Two scenarios:
- `_dev/build/build.yml` does not exist:
    - Output:
      ```
      2023/04/20 15:47:23 DEBUG Resolve external fields
      2023/04/20 15:47:23 DEBUG Build manifest hasn't been defined for the package
      ```

- `_dev/build/build.yml` exists without ECS reference:
    - Contents of `_dev/build/build.yml`:
      ```
      dependencies:
      ```
    - Output:
      ```
      2023/04/20 15:57:09 DEBUG Resolve external fields
      2023/04/20 15:57:09 DEBUG Package doesn't have any external dependencies defined
      ```
