### ISSUE TITLE
Add support for runtime fields

### ISSUE THREAD

**Issue by mrodm** [elastic/elastic-package#1229]
Relates https://github.com/elastic/package-spec/issues/39

Once runtime fields are allowed as part of fields in packages, it needs to be added the needed support in elastic-package:
- Check those runtime fields during the system tests (check the type and existance of those in the `fields` from the documents retrieved from Elasticsearch (https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime.html)
  > Use the fields parameter on the _search API to [retrieve the values of runtime fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-retrieving-fields.html). Runtime fields won’t display in _source, but the fields API works for all fields, even those that were not sent as part of the original _source.
- Add some label or mark in the generated Readmes to identify which fields are runtime fields. Some possible options for this:
    - Add a new column:
      | Field | Description | Type | Runtime |
      |---|---|---|---|
      | @timestamp | Event timestamp. | date | True |
    - Add `runtime` in the column **Type**:
      | Field | Description | Type |
      |---|---|---|
      | @timestamp | Event timestamp. | date (runtime) |

**Comment by mrodm** [comment]
Following what commented in https://github.com/elastic/elastic-package/issues/1111#issuecomment-1571834644 , adding a new column or more information could worsen the readibily of the docs itself. And it looks like that those runtime fields could be transparent for the users of this integration/input package.

**Comment by mrodm** [comment]
While working on #2208 
We have observed that if there are some failures in runtime fields, they are already reported by the tests or kibana.
Examples tested:
- Compile error: typo in function `em` instead of `emit`
    - Definition:
      ```yaml
      - name: day_of_week
        type: keyword
        runtime: "em(doc['@timestamp'].value.dayOfWeekEnum.getDisplayName(TextStyle.FULL, Locale.ENGLISH))"
      ```
    - Error:
      ```
      Error: failed to setup system runner: can't install the package: there was an apply error: installation failed: can't install the package: could not zip-install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"mapper_parsing_exception\n\tCaused by:\n\t\tscript_exception: compile error\n\tRoot causes:\n\t\tscript_exception: compile error"}
      ```
- Field does not exist: `@timap` instead of `@timestamp`:
     - Definition:
      ```yaml
      - name: day_of_week
        type: keyword
        runtime: "emit(doc['@timamp'].value.dayOfWeekEnum.getDisplayName(TextStyle.FULL, Locale.ENGLISH))"
      ```
    - Error:
      ```
      Error: error running package system tests: could not complete test run: failed to search docs for data stream metrics-elastic_package_registry.metrics-23409: [400 Bad Request] {"error":{"root_cause":[{"type":"script_exception","reason":"runtime error",...,"caused_by":{"type":"illegal_argument_exception","reason":"No field found for [@timamp] in mapping"}}}]},"status":400}
      ```
