### ISSUE TITLE
add ability to set publish ports to `config.yml`

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-package#1262]
Previously we could edit `snapshot.yml` and change the publish ports to do things like listen on a different network interface from localhost.  With #1140 we can't do that anymore because `snapshot.yml` gets overwritten every time "stack up" is called.

Use Case:  When testing different OSes, for example you want the stack running on Linux, but an elastic-agent running on Windows.

**Comment by dot-mike** [comment]
Any update to this? An idea could be to support multiple compose files: https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/#understanding-multiple-compose-files
and use the `!override` feature to replace value https://docs.docker.com/reference/compose-file/merge/#replace-value

Command to boot the stack would then be: `docker compose -f docker-compose.yml -f docker-compose.override.yml up -d`


A base `docker-compose.yml` file:

```
services:
  kibana:
    image: "${KIBANA_IMAGE_REF}"
    ports:
      - "127.0.0.1:5601:5601"
```

Override port mapping for kibana with file `docker-compose.override.yml`

```
services:
  kibana:
    ports: !override
      - "0.0.0.0:5601:5601"
```

This results in:

```
services:
  kibana:
    image: "${KIBANA_IMAGE_REF}"
    ports:
      - "0.0.0.0:5601:5601"
```


-----

I had the need to access Kibana on port 5601 in Docker using WSL, but from Windows., I can't access 127.0.0.1 directly in Windows.   So I would like to change listening host for 5601. But this is not possible.

A workaround for now is using socat to access Kibana with WSL for port-forwarding to 5600 so I can access on port 5600 in Windows which Socat listen on for the WSL IP-address.

```bash
elastic-package stack up -d -s elasticsearch,kibana
HOST=$(ip addr show eth0 | grep 'inet\b' | awk '{print $2}' | cut -d/ -f1)
# note that ssl is enabled with stack so we need to listen on SSL with port 5600
socat OPENSSL-LISTEN:5600,cert=$HOME/.elastic-package/profiles/default/certs/kibana/cert.pem,key=$HOME/.elastic-package/profiles/default/certs/kibana/key.pem,verify=0,fork OPENSSL:127.0.0.1:5601,verify=0

curl -vv -k https://172.25.208.198:5600/
> GET / HTTP/1.1
> Host: 172.25.208.198:5600
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 302 Found
< location: /login?next=%2F
```
