### ISSUE TITLE
elastic-package test pipeline fails when reroute processors are defined in both pipeline and routing_rules.yml

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/elastic-package#1387]
When routing_rules.yml looks like this:
```
- source_dataset: awsfirehose.log
  rules:
    - target_dataset: aws.cloudtrail
      if: ctx['aws.cloudwatch.log_stream'].contains('CloudTrail')
      namespace:
        - "{{labels.data_stream.namespace}}"
        - default
```

and ingest_pipeline/default.yml looks like this:
```
---
description: Pipeline for rerouting logs streams from Amazon Kinesis Data Firehose.
processors:
  - set:
      field: ecs.version
      value: 8.0.0
  - set:
      field: cloud.provider
      value: aws
  - reroute:
      if: ctx['aws.cloudwatch.log_stream'].contains('CloudTrail')
      dataset: aws.cloudtrail
      namespace: default
on_failure:
  - set:
      field: error.message
      value: "{{ _ingest.on_failure_message }}"```
I get this error when I run `elastic-package test pipeline -d log --generate`:
```
kaiyansheng ~/go/src/github.com/elastic/integrations/packages/awsfirehose [firehose_integration_package] $ elastic-package test pipeline -d log --generate
2023/08/09 16:25:45  WARN CommitHash is undefined, in both /Users/kaiyansheng/.elastic-package/version and the compiled binary, config may be out of date.
Run pipeline tests for the package
Error: error running package pipeline tests: could not complete test run: unmarshalling ingest pipeline content failed: yaml: unmarshal errors:
  line 14: cannot unmarshal !!str `aws.clo...` into []string
  line 16: cannot unmarshal !!str `default` into []string
```
