### ISSUE TITLE
[Secrets] Add a validation to check for variables that are candidates for `secret: true`

### ISSUE THREAD

**Issue by kpollich** [elastic/elastic-package#1554]
As part of the effort to drive adoption for secrets and improve the security of Fleet and Integrations, we'd like to start notifying integration maintainers when their integrations contain variables that are candidates for secrets. 

"Candidate" fields should include, but aren't limited to
- Variables of type `password`
- Variables with common names like `password` or `api_key` or `api_token`
- ...

This notice/warning should not be blocking at this time, and should just serve to notify users. 

We should also have a way to ignore this warning by decorating a given variable definition with a comment or flag e.g.

```yml
my_variable:
  # elastic-package-ignore/should-be-secret
  api_key: 
    type: string
```

**Comment by jsoriano** [comment]
> We should also have a way to ignore this warning by decorating a given variable definition with a comment or flag e.g.

We don't have a mechanism to ignore errors based on comments, but we can add an error code so it can be ignored by error code. The problem with this approach is that is not fine-grained, it would disable the check for the whole package.

I think that it could be enough with require `secret` for the discovered fields, so for the given example validation would succeed with `secret: false`:
```
my_variable:
  api_key: 
    type: string
    secret: false
```

This way we force package developers to make a decision on these potentially sensitive variables.
