### ISSUE TITLE
Data stream datasets are not picked up dynamically for Input type packages

### ISSUE THREAD

**Issue by ShourieG** [elastic/elastic-package#1806]
Currently for Input packages, elastic-package does not seem to be picking up datastream.dataset defined under vars:
Example - 
```yml
service: google-cloud-storage-emulator
input: gcs
vars:
  project_id: testproject
  alternative_host: "http://{{Hostname}}:{{Port}}"
  data_stream.dataset: google_cloud_storage.generic
  buckets: |
    - name: testbucket
      poll: true
      poll_interval: 15s
```
elastic-package always defaults to the convention of **{{package_dir_name}}.{{policy_template_name}}** for input packages, since input packages lack the data stream directory. This causes the issue where testing input packages with custom data streams that break the **{{package_dir_name}}.{{policy_template_name}}** convention, to become impossible.
