### ISSUE TITLE
[System test runner] Allow input selection from config.yml

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elastic-package#186]
For data streams that have multiple input options ([example](https://github.com/elastic/integrations/blob/9e4efb410dc4495a4805b69afc1bcbb79d9d8829/packages/cisco/data_stream/ios/manifest.yml#L40-L41)) in their `manifest.yml`, I would like a way to select the stream under test via the test's `config.yml`.

Perhaps allowing the input type to be specified from the config.yml would address this? Currently the system test runner always enables the first stream in the list.

```
input: logfile
vars: ~
data_stream:
  vars:
    paths:
      - "{{SERVICE_LOGS_DIR}}/*.log"
```
