### ISSUE TITLE
Pipeline test config panics if fields is empty

### ISSUE THREAD

**Issue by jsoriano** [elastic/elastic-package#2051]
Parsing pipeline test config panics if the `fields` attribute is empty. This can be reproduced for example by trying to skip a test with something like the following:
```
skip:
  reason: New value in network.community_id when running on newer versions
  link: https://github.com/elastic/integrations/issues/10904
```

Configuring it like this works:
```
skip:
  reason: New value in network.community_id when running on newer versions
  link: https://github.com/elastic/integrations/issues/10904
fields: 
  tags: []
```
