### ISSUE TITLE
Automatic `tag` generation for ingest pipeline processors

### ISSUE THREAD

**Issue by chrisberkhout** [elastic/elastic-package#2131]
Manually maintaining `tag` values for processors in ingest pipelines is time consuming and can lead to confusion if processor settings drift away from the meaning captured in a `tag` value.

Good `tag` values can be generated automatically by combining the processor name with the values of certain processor options (best chosen based on the processor type), normalizing that, and adding a number if necessary for uniqueness within a pipeline.

An example with a generated tag name:
```yaml
- set:
    tag: set_destination_ip
    field: destination.ip
    copy_from: parsed_json.ip
```

A rough POC can be found in [`tag-processors.py`](https://gist.github.com/chrisberkhout/5084336ece24a54007826bb92f501f9e).

This could be made part of `elastic-package format`, or it could be a separate command.
