### ISSUE TITLE
[K8s service deployer] Configure kube-proxy to expose metrics

### ISSUE THREAD

**Issue by ChrsMark** [elastic/elastic-package#315]
`kube-proxy` will not expose metrics endpoint by default with kind setup. We need to manually edit `kube-proxy` configmap and delete the pod so as to have it recreated properly.

This is something that could be improved on `kind`'s side by having an option to enable metrics exposition by default (see https://github.com/kubernetes-sigs/kind/issues/2184), however we might can to tackle this on our side and have the deployer to edit the confgimap and delete the Pod so as to have a new one created with the proper configuration. We can first check if the endpoint is reachable so as to avoid recreating the pod without reason.

@mtojek @ycombinator what do you think about this?

**Comment by ChrsMark** [comment]
Related to https://github.com/elastic/integrations/issues/822

**Comment by ChrsMark** [comment]
We can define how to deploy kind cluster on our side to patch this setting as indicated in kind's issue:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: KubeProxyConfiguration
    metricsBindAddress: "0.0.0.0"
```
