### ISSUE TITLE
Field validator should check for ECS fields marked as arrays

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elastic-package#615]
It would be helpful if elastic-package could trigger errors on ECS event fields that are not arrays. For example, [host.ip](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-ip) is specified to be an array so events that contain the field should be an array of ips.

<img width="745" alt="Screen Shot 2021-12-08 at 8 49 04 AM" src="https://user-images.githubusercontent.com/4565752/145219412-387a58ea-a250-494e-9d15-de5d35623809.png">

The generated YAML specification indicates the array type. https://github.com/elastic/ecs/blob/9b463c9116eb594a3be10db01c3236fd6b44b996/generated/ecs/ecs_flat.yml#L4536-L4543

```yaml
host.ip:
  dashed_name: host-ip
  description: Host ip addresses.
  flat_name: host.ip
  level: core
  name: ip
  normalize:
  - array
  short: Host ip addresses.
  type: ip
```
