### ISSUE TITLE
[Discuss] Add support for OpenShift service deployer

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#672]
The Cloud Native Monitoring Squad is working on [running and testing the Elastic Agent in the OpenShift cluster](https://github.com/elastic/integrations/issues/2065). It might be a good idea to add official support for it in `elastic-package`, similarly, we did for Kubernetes.

My first thought is to introduce support for `minishift` as we did for `kind`. Let's consider this as kick-off point.

Related: https://github.com/elastic/integrations/issues/2065

cc @ChrsMark @tetianakravchenko  @jsoriano

**Comment by mtojek** [comment]
@ChrsMark quote in  https://github.com/elastic/integrations/issues/2065#issuecomment-1023021504: 

> That would be great! In the past we had thought about supporting Openshift in our CI but in Beats CI it was a bit more complicated. Now with elastic-package it should be more straight-forward. I'm wondering if it would make sense to use a local "cluster" or a cloud one on GCP for a more official approach. The second one would be more expensive if the cluster is always up but we can verify this with infra team. I think that ECK team does the same to test the operator.

**Comment by tetianakravchenko** [comment]
> My first thought is to introduce support for minishift as we did for kind. Let's consider this as kick-off point.

Minishift runs only OpenShift 3.x clusters, for OpenShift 4.x should be used https://github.com/code-ready/crc

**Comment by mtojek** [comment]
Thanks for bringing it up, good catch!

**Comment by tetianakravchenko** [comment]
> I'm wondering if it would make sense to use a local "cluster" or a cloud one on GCP for a more official approach. The second one would be more expensive if the cluster is always up but we can verify this with infra team. I think that ECK team does the same to test the operator.

I would try local setup first with crc

**Comment by mtojek** [comment]
I understand that this is an unknown area, but do you suppose that there might be incompatibilities between OpenShift and our current Kubernetes YAML for agent?

**Comment by tetianakravchenko** [comment]
@mtojek do you mean comparing to this manifest https://github.com/elastic/beats/blob/master/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml ?

if yes - there will be some configuration difference for Openshift - https://github.com/elastic/beats/pull/30054/files (still WIP)

**Comment by mtojek** [comment]
I was thinking rather about [elastic-package's fork](https://github.com/elastic/elastic-package/blob/main/internal/testrunner/runners/system/servicedeployer/elastic-agent-managed.yaml.tmpl), but yes, that was my question about.

**Comment by Protopopys** [comment]
@mtojek  you may need the SecurityContextConstraints and additional rights for the SecurityContextConstraints in the Role.
SecurityContextConstraints
```
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: elastic-agent-scc
  labels:
    app.kubernetes.io/name: elastic-agent-scc
    app.kubernetes.io/version: "7.16.3"
    app.kubernetes.io/component: elastic-agent
    app.kubernetes.io/part-of: elastic-stack
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - hostPath
  - persistentVolumeClaim
  - projected
  - secret
allowHostNetwork: true
allowHostPorts: true
allowHostPID: true
allowHostIPC: true
readOnlyRootFilesystem: false
allowedCapabilities: []
requiredDropCapabilities: []
defaultAddCapabilities: []
```

Role
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elastic-agent-role
  namespace: elastic-stack
  labels:
    app.kubernetes.io/name: elastic-agent-role
    app.kubernetes.io/version: "7.16.3"
    app.kubernetes.io/component: elastic-agent
    app.kubernetes.io/part-of: elastic-stack
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]

  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - elastic-agent-scc
```
