### ISSUE TITLE
Make terraform outputs available as variables in tests

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elastic-package#703]
This is a feature request to make the data from `terraform outputs -json` available in system tests. An example use case is a test that creates an S3 bucket and SQS topic and needs information about those resources in the test case.

```hcl
# _dev/deploy/tf/outputs.tf

output "queue_url" {
  value = aws_sqs_queue.test-queue.url
}
```

And then be able to reference those values in some way in test parameters.

```yaml
# _dev/test/system/test-awss3-config.yml

input: aws-s3
data_stream:
  vars:
    access_key_id: "{{{ AWS_ACCESS_KEY_ID }}}"
    secret_access_key: "{{{ AWS_SECRET_ACCESS_KEY }}}"
    queue_url: "{{{ TF_OUTPUT_queue_url }}}"
```
