### ISSUE TITLE
[system testing] Add assertion for expected number of events

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elastic-package#821]
In some system tests we have a fixed number of events that are reproducible for each run. In order to verify the input configuration is working as expected I would like to be able to assert that the system test produced a specific number of events.

For example, in an integration that uses the httpjson input to request events from an API I want to validate that input requests the initial batch, makes requests to paginate, and then makes a follow up request after some interval. Given that we mock the API responses we know the expected number of events that we should have after all of those calls complete. So if the test had an assertion then we could validate this behavior.

An example config file for such a test:

```
input: httpjson
service: cloudflare
vars:
  api_url: http://{{Hostname}}:{{Port}}
  ssl.verification_mode: none
data_stream:
  vars:
    preserve_original_event: true
    auth_email: user@example.com
    auth_key: xxxxxxxxxx
    account: aaabbbccc

# PROPOSED
system_test:
  expected_event_count: 10
```
