### ISSUE TITLE
[field validation] Check values against ECS expected_values

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elastic-package#864]
ECS added an `expected_values` list its schema to facilitate data validation. `elastic-package` should check data against this list when validating documents.

```
- name: faas
  fields:
    - name: trigger.type
      type: keyword
      expected_values:
        - http
        - pubsub
        - data source
        - timer
        - other
```

- https://github.com/elastic/ecs/pull/1952
