### ISSUE TITLE
[System test runner] Assert that fields in event document are in fields.yml

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#90]
Follow up to #64.

Currently the system test runner simply checks if documents are present in the appropriate data stream. A next step would be to parse the fields from those documents and check if they match up with the ones defined in the package/dataset's `fields.yml` files.

**Comment by mtojek** [comment]
I'm going with this feature.

**Comment by mtojek** [comment]
This might be a bit complex that I though due to wildcards. See the AWS `package-fields.yml`:

```yaml
- name: aws
  type: group
  fields:
    - name: tags.*
      type: object
      description: |
        Tag key value pairs from aws resources.
    - name: s3.bucket.name
      type: keyword
      description: |
        Name of a S3 bucket.
    - name: dimensions.*
      type: object
      description: |
        Metric dimensions.
    - name: '*.metrics.*.*'
      type: object
      description: |
        Metrics that returned from Cloudwatch API query.
```

It looks like `*.metrics.*.*` is a catch-all object definition.

**Comment by ycombinator** [comment]
Hmmm, might be worth looking into how the `aws` module in Metricbeat is handling this?

**Comment by ycombinator** [comment]
> Hmmm, might be worth looking into how the `aws` module in Metricbeat is handling this?

Looks like it's not :) There is no system test for the `aws` Metricbeat module in Beats: https://github.com/elastic/beats/tree/master/x-pack/metricbeat/module/aws

**Comment by exekias** [comment]
One option to avoid mismatches between Kibana implementation and whatever we do is to is actually use the installed integration. Send events to the index and check the resulting mapping there

**Comment by ycombinator** [comment]
>  Send events to the index and check the resulting mapping there

This might work for most cases. But IIRC there is some setting available in `fields.yml` that causes a field not to be mapped. Let me see if I can find it...

**Comment by ycombinator** [comment]
I think I was thinking of the `default_field: false` setting available on fields in `fields.yml`, but that does not impact whether the field shows up in the ES template mapping or not. So I think we are good here to check against the resulting mapping.

**Comment by mtojek** [comment]
Thank you for your input, @exekias . I'm not sure if I follow the idea. Do you think we can use the Get field mapping API? See: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-field-mapping.html

**Comment by ycombinator** [comment]
I think you can just get the entire mapping for a data stream, no? And then, for each field in the event document, ensure that that field is defined in the mapping.

**Comment by exekias** [comment]
Yes to both things. Problem is that by default all fields will be mapped, either based on the template definition or the automatic mapping that ES assigns. I think index settings would need to be updated in order to disable dynamic mapping: https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html, setting it to `false` would work

**Comment by ycombinator** [comment]
Just to step back a bit from the idea of checking the mapping, maybe I'm missing something but why can't we compare fields in the event document with fields in `fields.yml` files? For fields whose paths are defined using wildcards isn't it a matter of checking that the field path in the event document conforms to the field path (with or without wildcards) from the `fields.yml` files? As @mtojek this could be achieved with a custom comparator (something glob-like)?

**Comment by mtojek** [comment]
> Just to step back a bit from the idea of checking the mapping, maybe I'm missing something but why can't we compare fields in the event document with fields in fields.yml files?

Yes, that is my idea to do this, as it looks much simpler. 

> For fields whose paths are defined using wildcards isn't it a matter of checking that the field path in the event document conforms to the field path (with or without wildcards) from the fields.yml files? 

Both solutions, `fields.yml` and Mapping API, have the same issue. If developer defines a catch-all field like:

```yaml
    - name: '*.metrics.*.*'
      type: object
      description: |
        Metrics that returned from Cloudwatch API query.
```

we'll never document or list any fields in docs.

> As @mtojek this could be achieved with a custom comparator (something glob-like)?

If you don't mind I would start with that one, unless the solution depending on Kibana index mapping is easier to implement. I wouldn't worry about inconsistency as the integrations are installed us bundles (all files in).
