### ISSUE TITLE
System tests fail because fields (counts,values) under histogram type are not defined 

### ISSUE THREAD

**Issue by mrodm** [elastic/elastic-package#905]
While running system tests again a new integration that indexes histogram metrics, I see that even having defined the histogram field:
```yaml
- name: package_registry.http
  type: group
  fields:
    - name: request_duration_seconds.histogram
      type: histogram
      description: >
        A histogram of latencies for requests to the http server

```
there are failures regarding the sub-fields are not defined:
```
FAILURE DETAILS:
elastic_package_registry/metrics default:
[0] field "package_registry.http.request_duration_seconds.histogram.counts" is undefined
[1] field "package_registry.http.request_duration_seconds.histogram.values" is undefined
```

This is solved by defining those sub-fields:
```diff
       description: >
         A histogram of latencies for requests to the http server

+    - name: request_duration_seconds.histogram.counts
+      type: long
+      description: >
+        Counters of the histogram of latencies for requests to the http server
+
+    - name: request_duration_seconds.histogram.values
+      type: double
+      description: >
+        Bucket values of the histogram of latencies for requests to the http server
+
```

Independent of adding those fields definitions, once the integration is installed, those mappings are not present:
```json
       "http":  {
          "properties": {
            "request_size_bytes": {
              "properties": {
                "histogram": {
                  "type": "histogram"
                }
              }
            },
            "response_size_bytes": {
              "properties": {
                "histogram": {
                  "type": "histogram"
                }
              }
            },
            "request_duration_seconds": {
              "properties": {
                "histogram": {
                  "type": "histogram"
                }
              }
            }
          }
        }
```

Should these sub-fields (counts and values) of histogram be skipped while running the tests ?
